### ISSUE TITLE
Remove Guard dependency

### ISSUE THREAD

**Issue by rehsack** [miyagawa/LWP-Protocol-PSGI#7]
Because Guard has no reasonable terms of use (no LICENSE or COPYING file, no line in documentation regarding that, nothing specified in META-files), it's risky to use Guard.

**Comment by miyagawa** [comment]
The distribution has a COPYING file stating it's licensed under the same terms as Perl itself. https://metacpan.org/source/MLEHMANN/Guard-1.023
